异常指的是导致程序中断执行的一种指令流。

可以使用的异常组合为：try...catch、try...catch...finally、try...finally

如果想获得完整的异常信息，则可以使用异常类中提供的 printStackTrace() 方法完成。eg：
```
try {
    ...
} catch(异常类 e) {
    e.printStackTrace();
}
```
即便有了异常处理语句，但是如果没有进行正确的异常捕获，那么程序也会导致中断执行，但是finally里的代码还是会被执行。


# 异常处理流程
1. 在程序运行的过程之中才会产生异常，而一旦程序执行中产生了异常之后将自动进行指定类型的异常类对象实例化处理
2. 如果此时程序之中并没有提供异常处理的支持，则会产生JVM默认异常处理方式，首先进行异常信息的打印然后直接退出异常的程序
3. 此时程序中如果存在有异常处理，那么这个产生的异常类实例化对象，将会被try语句捕获。
4. try捕获到异常之后与其匹配的catch中的异常类型进行依次比对，如果与catch中的类型相同，则认为应该使用此catch中的操作处理异常。如果没有任何的匹配进行成功。直接进入finally
5. 不管异常是否处理最终都要执行finally语句，但是当执行完成finally的程序，会进一步判断当前异常是否已经处理过了，如果处理过了，则继续向后执行其他代码，如果没有处理则转交由JVM进行默认的处理。



程序之中可以处理的异常的最大类型（不是运行之中）救赎Throwable, 它有两个子类
1. Error:     此时程序还未执行时出现的错误，开发者无法处理
2. Exception: 程序运行中出现的异常，开发者可以处理

通过分析可以发现异常产生的时候会产生异常的实例化对象，那么按照对象的向上转型可以转型成Exception,所有的异常都可以用Exception来处理，在进行异常处理的时候，要把捕获大的异常范围放在捕获范围小的异常之后。

# throws关键字
如果明确的表明该方法可能产生哪种异常，那么此时就可以在方法声明上使用throws关键字来进行异常类型的标注
```java
classs MyMath {
    public static int div(int x, int y) throws ArithMeticException {
        return x / y;
    }
}
public class JavaDemo {
    public static void main(String args[]) {
        try {
            System.out.println(MyMath.div(10, 2));
        } catch (ArithMeticException e) {
            e.printStackTrace();
        }
    }
}
```
也可以在主方法上继续抛出异常，如果出错则默认处理
```java
public class JavaDemo {
    public static void main(String args[]) throws ArithMeticException {
        System.out.println(MyMath.div(10, 2));
    }
}
```


# throw 关键字
throw关键字表示进行手工异常的抛出，即此时 将手工产生一个异常类的实例化对象，并且进行异常的抛出处理
```java
public class JavaDemo {
    public static void main(String args[]) {
        try{
            throw new Exception("自己抛的玩的对象");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
```

# RuntimeException
```java
public class JavaDemo {
    public static void main(String args[]) {
        int num = Integer.parseInt("123");
    }
}
```
观察Intger类中的parseInt()方法如下
```
public static int parseInt(String s,int radix) throws NumberFormatException
```
但是主方法并没有强制要求处理NumberFormatException异常因为是RuntimeException的子类

RuntimeException的子类可以不需要强制性处理


# 自定义异常类
有两种实现方式，继承Exception或者继承RuntimeException
```java
class BombException extends Exception {
    public BombException(String msg) {
        super(msg);
    }
}
```

# 断言 assert
从JDK1.4开始追加有一个断言的功能，确定代码执行到某行后一定是所期待的结果，并不一定是准确的，也有可能出现偏差，但是这种偏差不应该影响程序的正常执行。
```java
public class JavaDemo {
    public static void main(String args[]) {
        int x = 10;
        assert x == 100 : "x的内容不是100";
        System.out.println(x);
    }
}
```
上述代码能正常执行到system,如果现在想要执行断言，则必须在程序执行的时候加入参数如下
```
$> java -ea JavaDemo
```
所以在Java里面并没有将断言设置为一个程序必须执行的步骤，需要特定环境下才可以开启


在以下4种特殊情况下，finally 块不会被执行
1. finally 语句块第一行发生了异常。因为在其他星，finally 块还是会得到执行
2. 在前面的代码块种用了 System.exit(int) 已退出程序。exit 是带参函数；若该语句在异常语句之后，finally 会执行
3. 程序所在的线程死亡
4. 关闭 CPU




